version: '3.4'

services:
  node_1:
    build:
      context: ../
      args:
        PROJECT: bitcanna
        PROJECT_BIN: bcnad
        PROJECT_DIR: .bcna
        VERSION: v3.0.0
        REPOSITORY: https://github.com/BitCannaGlobal/bcna
        NAMESPACE: BCNAD
        BUILD_IMAGE: binary_zip
        BINARY_URL: https://github.com/BitCannaGlobal/bcna/releases/download/v3.0.0/bcna_linux_amd64.tar.gz
    ports:
      - '26656:26656'
      - '26657:26657'
      - '1317:1317'
    environment:
      - MONIKER=node_1
      - CHAIN_JSON=https://raw.githubusercontent.com/cosmos/chain-registry/master/bitcanna/chain.json
      - P2P_POLKACHU=1
      - STATESYNC_POLKACHU=1
    env_file:
      - ../.env
    volumes:
      - ./node-data:/root/.bcna
